src/components/atoms/button/index.js
src/components/atoms/image/index.js
src/components/atoms/input/index.js
src/components/atoms/textarea/index.js

add atoms/button, input, image, textarea

[ESC-107] feat: Add atoms/button input image textarea

---

.eslintrc
src/components/atoms/avatar/index.js
src/components/atoms/icon/index.js
src/components/atoms/text/index.js

Add { atoms/avatar, atoms/icon, atoms/text } components

[ESC-106] feat: Add atoms/avatar icon text component

---

src/components/atoms/button/index.js
src/components/atoms/index.js
src/components/atoms/input/index.js
src/components/atoms/text/index.js
src/components/atoms/textarea/index.js

- [ESC-110](https://earth-saving-cleaner.atlassian.net/browse/ESC-110)
-atoms index.js 파일에서 import export에러 발생
-에러명 ex) Avatar not found in "./Avatar"
-theme파일 루트 설정 잘못 표기됨
-에러명 ex) Module not fount: Error: can't resolve ~(경로)
-export default로 export해 주었기때문에 import 시 bracket이 필요없다. 
-root설정 제대로 표시해줌. (Button, Input, Text, Textarea) => import themes from "../../../theme/theme";

[ESC-110] Fix: fix root and import export

---

package.json
src/configureStore.js
src/modules/rootSaga.js
yarn.lock

- [[Front]Fix errors occurred after merging](https://earth-saving-cleaner.atlassian.net/browse/ESC-121)
- merge 후 configureStore, saga가 제대로 작동하지 않아 dispatch가 실행되지 않는 상황 해결
- redux-logger 라이브러리 추가

Esc 121 front fix errors occurred after merging

---

src/components/organisms/CommentFooter/index.js
src/components/templates/CommentTemplate/index.js
src/components/templates/Modal/index.js
src/components/templates/Portal/index.js

fix: revert deleted files

---

src/api/index.js
src/hooks/useInfinitescroll.js
src/modules/sagas/feed.js
src/modules/slices/feedSlice.js

fix: reset commit

---

src/components/atoms/icon/index.js
src/components/organisms/Header/index.js

- [Front - Update header](https://earth-saving-cleaner.atlassian.net/browse/ESC-139)
- add plogging navigator to header
- navigation 로직 수정
- 렌더링 테스트 완료
[ESC-139]: https://earth-saving-cleaner.atlassian.net/browse/ESC-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ESC-139] add plogging navigator, edit logic for select nav

---

.eslintrc
src/components/App.js
src/components/atoms/ClusterCircle/index.js
src/components/atoms/index.js
src/components/pages/MapClusteringPage/index.js
src/components/pages/index.js
src/theme/theme.js

- [ESC 95 - map clustering](https://earth-saving-cleaner.atlassian.net/browse/ESC-95)
- 클러스터링 circle 컴포넌트 생성
- 클러스터링 map page 생성
- 화면 렌더링 테스트 완료
- DB에 mock data가 부족해서 mock data 생성 후 테스트가 필요합니다.

[ESC 95] front-map clustering

---

src/components/pages/MainPage/index.js

- [esc-143](https://earth-saving-cleaner.atlassian.net/browse/ESC-143)
- button 클릭시 feedid를 보내주지 못하는 상황 발생 -> 수정
-
- yarn start debugging
-

[esc-143]fix: like button click

---

src/api/index.js
src/components/atoms/ClusterCircle/index.js
src/components/atoms/Text/index.js
src/components/atoms/index.js
src/components/organisms/Header/index.js
src/components/pages/MapClusteringPage/index.js
src/components/pages/MapPage/index.js
src/components/pages/index.js
src/components/templates/MyPageGrid/index.js
src/components/templates/QuestResultTemplate/index.js
src/components/templates/QuestTemplate/index.js

- [Esc-148](https://earth-saving-cleaner.atlassian.net/browse/ESC-148)
- warning error 해결
src/api/index.js
src/components/atoms/ClusterCircle/index.js
src/components/atoms/index.js
src/components/atoms/text/index.js
src/components/organisms/Header/index.js
src/components/pages/MainPage/index.js
src/components/pages/MapClusteringPage/index.js
src/components/pages/MapPage/index.js
src/components/pages/index.js
src/components/templates/MyPageGrid/index.js
src/components/templates/QuestResultTemplate/index.js
src/components/templates/QuestTemplate/index.js
수정
-

Esc 150 fix console error

---

src/components/organisms/Header/index.js

- [esc-151]
- icon waring error 해결
-
-

[esc-151]fix: solve iconclick warning

---

src/api/index.js
src/components/pages/MyPage/index.js
src/components/templates/MyPageTemplate/index.js

[155] console error fix and add like button bug fix
- [[Front] Fix console error and like increment bug fix](https://earth-saving-cleaner.atlassian.net/browse/ESC-155)
-console error fix (무한 스크롤 문제 제외)
-like 버튼 클릭 시,
backend 로직에는 미들웨어 사용중이나, 프론트에서 헤더에 토큰 안보내는 오류 있어서 수정함
- yarn start
[ESC-155]: https://earth-saving-cleaner.atlassian.net/browse/ESC-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ESC-155] fix: console error and like increment

---

src/components/organisms/NewFeed/index.js

- [ESC-161 update preview image src](https://earth-saving-cleaner.atlassian.net/browse/ESC-161)
- preview image url s3 original 디렉토리로 변경
[ESC-161]: https://earth-saving-cleaner.atlassian.net/browse/ESC-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ESC-161] update: preview image src

---

src/components/organisms/NewFeed/index.js

- [ESC 162 update feed register logic](https://earth-saving-cleaner.atlassian.net/browse/ESC-162)
- 피드 등록 로직 수정

[ESC 162] update: feed register logic

---

src/components/pages/MainPage/index.js

제목 예시: [17] 메인페이지 UI
- [esc-163](https://earth-saving-cleaner.atlassian.net/browse/ESC-163)
- 피드상세 좋아요 버튼 클릭 오류 수정
-
-yarn start

fix: feed detail like button bug

---

src/components/pages/MainPage/index.js
src/constants/index.js
src/hooks/useInfinitescroll.js
src/modules/sagas/feed.js

- [Front-update infinite scroll paging logic](https://earth-saving-cleaner.atlassian.net/browse/ESC-165)
- 무한 스크롤 페이징 처리 로직 보완

feat: update infinite scroll paging logic

---

src/components/organisms/UserCard/index.js
src/components/pages/MainPage/index.js
src/components/pages/MapClusteringPage/index.js
src/components/pages/MyPage/index.js
src/components/templates/QuestTemplate/index.js

- [카드 제목](https://earth-saving-cleaner.atlassian.net/browse/ESC-168)
- warning 및 comment send 오류 해결
-
-
-

fix: warning bug and comment send error

---

src/components/pages/MapClusteringPage/index.js
src/components/pages/MapPage/index.js
src/components/templates/QuestTemplate/index.js

제목 예시: [17] 메인페이지 UI
- [ESC-170](https://earth-saving-cleaner.atlassian.net/browse/ESC-170)
- zoom level 변경 및 quest modal 레이아웃 변경
-
-yarn start
- 
[ESC-170]: https://earth-saving-cleaner.atlassian.net/browse/ESC-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: quest modal ui and zoom level

---

src/components/atoms/Avatar/index.test.js
src/components/atoms/Button/index.js
src/components/atoms/Button/index.test.js
src/components/atoms/ClusterCircle/index.js
src/components/atoms/ClusterCircle/index.test.js
src/components/pages/MapPage/index.js

제목 예시: [17] 메인페이지 UI
- [ESC-177](https://earth-saving-cleaner.atlassian.net/browse/ESC-177)
- Atoms/ Button, Avatar test
-
- yarn test
- 
[ESC-177]: https://earth-saving-cleaner.atlassian.net/browse/ESC-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ESC-177] test: Atoms Button Avatar ClusterCircle

---

README.md

- [ESC-92 - Write Readme](https://earth-saving-cleaner.atlassian.net/browse/ESC-92)
- 리드미 작성(초안)
- 추후 보완 예정
[ESC-92]: https://earth-saving-cleaner.atlassian.net/browse/ESC-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ESC-92]Write Readme
